CREATE TABLE public.orders
(
	ORDER_NO CHARACTER(5) NOT NULL,
	PURCH_AMT NUMERIC(16,2),
	ORD_DATE DATE,
	CUSTOMER_ID CHARACTER(4),
	SALESMAN_ID CHARACTER(4),
	PRIMARY KEY (ORDER_NO),
	
	CONSTRAINT CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID)
    REFERENCES public.customer (CUSTOMER_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID,
	
    CONSTRAINT SALESMAN_ID FOREIGN KEY (SALESMAN_ID)
    REFERENCES public.salesman (SALESMAN_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID
);

ALTER TABLE IF EXISTS public.orders
    OWNER to postgres;