CREATE TABLE public.customer
(
	CUSTOMER_ID CHARACTER(4) NOT NULL,
	CUST_NAME CHARACTER(20),
	CITY CHARACTER(20),
	GRADE INTEGER,
	SALESMAN_ID CHARACTER(4),
	PRIMARY KEY (CUSTOMER_ID),
	
    CONSTRAINT SALESMAN_ID FOREIGN KEY (SALESMAN_ID)
    REFERENCES public.salesman (SALESMAN_ID) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID
);

ALTER TABLE IF EXISTS public.customer
    OWNER to postgres;